# Generated by Django 4.1.1 on 2022-09-11 13:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_profile',
            new_name='UserProfileInfo',
        ),
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='profile_Pic',
            new_name='profile_pic',
        ),
    ]
