# Generated by Django 4.1.1 on 2022-09-17 05:18

import app_users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0003_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='user_types',
            new_name='user_type',
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='bio',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to=app_users.models.path_and_rename, verbose_name='Profile Picture'),
        ),
    ]
