# Generated by Django 4.1.1 on 2022-09-27 06:16

import app_users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0004_rename_user_types_userprofileinfo_user_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, upload_to=app_users.models.path_and_rename, verbose_name='Event Icon')),
                ('about', models.CharField(max_length=500)),
            ],
        ),
    ]
