# Generated by Django 4.1.1 on 2022-09-27 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_workingdays_timeslots_slotsubject'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='event',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
