# Generated by Django 4.1.1 on 2022-09-27 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_subject_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='event',
        ),
    ]
